[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3

[game_servers]
vm1 ansible_host=1.2.3.4
vm2 ansible_host=1.2.3.5

[db_servers]
vm3 ansible_host=1.2.3.6

# Falls alles auf einer VM läuft, einfach eine Gruppe nutzen
# und die anderen Gruppen weglassen.
