[all]
localhost ansible_connection=local

# Hosts in dieser Gruppe bekommen Docker installiert (roles/docker).
# Einfach den jeweiligen Hostnamen hier eintragen, z. B.:
#   webserver01
[docker]
docker01 ansible_connection=local
