---
- name: Base configuration on all servers
  hosts: all
  become: true
  roles:
    - base
    - node_exporter

- name: Install Docker (only on hosts listed in docker_hosts)
  hosts: all
  become: true
  roles:
    - role: docker
      when: ansible_hostname in docker_hosts
