---
# SSH
manage_ssh_config: false             # false = Ansible fasst sshd_config nicht an (Host regelt das schon selbst)
ssh_port: 22
ssh_permit_root_login: "no"          # "yes" nur falls du unbedingt als root per Passwort ran musst
ssh_password_authentication: "no"    # nur Key-Login erlauben

# Firewall: zusätzlich zu SSH offene Ports (Web, Game-Server-Ports, etc.)
firewall_allowed_tcp_ports:
  - "{{ ssh_port }}"
firewall_allowed_udp_ports: []

# Automatische Sicherheitsupdates
unattended_upgrades_enabled: true

# Zeitzone
server_timezone: "Europe/Berlin"

# Fail2ban aktivieren (Schutz gegen SSH-Bruteforce)
fail2ban_enabled: true
