---
# SSH
manage_ssh_config: false             # false = Ansible fasst sshd_config nicht an (Host regelt das schon selbst)
ssh_port: 22
ssh_permit_root_login: "no"          # "yes" nur falls du unbedingt als root per Passwort ran musst
ssh_password_authentication: "no"    # nur Key-Login erlauben

# Automatische Sicherheitsupdates
unattended_upgrades_enabled: true

# Zeitzone
server_timezone: "Europe/Berlin"

# Hardening
disable_ipv6: false                  # Auf true setzen, falls IPv6 nicht benötigt wird
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2

# Automatische Reboots bei Kernel-Updates
unattended_upgrades_reboot: false
unattended_upgrades_reboot_time: "04:00"
